### ISSUE TITLE
Is 'wav, vgm file out' not normally available?

### ISSUE THREAD

**Issue by msxanadian** [kuma4649/mucomDotNET#20]
I tried WAV output, but it doesn't work.  The same goes for VGM. 
Looking at the source, I don't think VGM has been implemented.
Hasn't it been implemented yet?

Just in case, I've debugged WAV.program.cs, and there's an exception here.
-------------------------      
   _drv = new Driver();
         ((Driver)drv).Init(
               lca
                    , bl.ToArray()
                    , null
                    , new object[] {
                          false
                        , false
                        , false
                    }
                    );_
------------------------
Is WAV not implemented yet too?

**Comment by kuma4649** [comment]
動かないですね。。。
そのうち直します！

**Comment by kuma4649** [comment]
TAG106 2021/07/15
にて修正しました。ご確認ください。

**Comment by kuma4649** [comment]
toVgmのほう、DotNETモードのデータの変換にバグがあるようです。
そのうち直します！

**Comment by msxanadian** [comment]
I'm surprised that the speed of the work is so fast.
I will test it soon.
Cheer up, buddy!

**Comment by msxanadian** [comment]
I've tested it rough now, and wav is playing very well. 
I also compared the VGM to wav and it looks fine. 

'_**toVgmのほう、DotNETモードのデータの変換にバグがあるようです。 そのうち直します！**_'

Does that mean there's more to be fixed in VGM?

**Comment by kuma4649** [comment]
通常のmucom88のデータは恐らく問題ないのですが、
(通常のmucom88 = OPNA x 1)
mucomDotNET独自の機能を利用したデータは上手く変換できていないことがわかってます。
(独自の機能 = OPNA x 2 + OPNB x 2)

**Comment by msxanadian** [comment]
I understood .   
あなたの作業をいつも応援します。 
ありがとうございます。

**Comment by kuma4649** [comment]
修正完了しました。ご確認ください！

**Comment by msxanadian** [comment]
The test files I use are made by MUCOM88, so just like yesterday's version, the result works without any problems.
If I find MUB files that can check the output of YM2610 in your source, I will test it secondarily.
Good Job Mr.

**Comment by kuma4649** [comment]
どうもありがとうございます！
機会がありましたらレポートお願いします(^_^

問題なさそうなので閉じますね。
