### ISSUE TITLE
MML、曲データー等の読み書きにファイルシステムに依存しないようにしてほしい

### ISSUE THREAD

**Issue by aosoft** [kuma4649/mucomDotNET#6]
モバイルやブラウザなど、ファイルシステムに自由にファイルの読み書きができない環境があるので、ファイルを前提にデーターの読み書きをする構造だとそのような環境で動かすことが難しくなります。

こういうケースは Stream クラスで読み書きを抽象化するのが定石だと思うので、そのような形にしていただきたいのです。
MUCOM の場合、 MML 内に記述した追加ファイルの読み込みがあるので、その辺りを考慮して疑似コードで定義案を作成しました。そちらも見ていただければと思います。

https://gist.github.com/aosoft/3c6461e827aed52057abcb1d2198c43b

**Comment by kuma4649** [comment]
どんどんやりましょうぞ

**Comment by aosoft** [comment]
大ざっぱには

* パス名を指定しているところを Stream にする
* 音色、PCM を読み込むための callback を用意する

の 2 点です。

MUCOM で扱うデーターは今どきの基準だと小さいサイズなので結局 byte[] で丸ごとオンメモリで扱う (今すでにそうなってますし) なら Stream ではなく byte[] でもよいと思います。
読み込みソースとしては byte[] ではなく IReadOnyList<byte> にしておいた方が配列だけではなく柔軟性が高くなります。

```csharp
static byte[] Compile(IReadOnyList<byte> sourceMML, Func<string, IReadOnyList<byte>> appendFileReaderCallback);
static void LoadMub(IReadOnyList<byte> mub, Func<string, IReadOnyList<byte>> appendFileReaderCallback);

**Comment by aosoft** [comment]
同様に MDSound の LoadRhythmSample も同じ話があります。

**Comment by aosoft** [comment]
Driver が対応してないですよー (むしろこっちの方が重要)
Driver が対応すれば MML コンパイル → 再生をファイル書き出しなしで実現できるようになります。

**Comment by aosoft** [comment]
よく確認したら mub 本体自体は byte[] で受けつていたのですね。すいません。
音色ファイル等の読み込み対応て PR 出しました。 (#14)

**Comment by aosoft** [comment]
本件 Close でよいと思います。ありがとうございましたー
