### ISSUE TITLE
StartToMmlData で dispMessage を渡さないようにした方がよい

### ISSUE THREAD

**Issue by aosoft** [kuma4649/mucomDotNET#7]
static な Log.writeMethod にセットしているので、 Compiler や Driver のインスタンスを同時に使用している場合に問題を起こす可能性があります。

Log.writeMethod はアクセスに制限がないので、

* StartToMmlData を呼ぶ前にセットしておいてもらうようにして StartToMmlData  の引数からは削除する
* StartToMmlData の呼び出し内でのみ使用する形に限定し、 Log クラス側に影響を与えないようにする

のどちらかにすべきと思います。

**Comment by kuma4649** [comment]
TAG032で恐らく対応済みなのでクローズします。。。
